name: MGBossesRedone
version: ${project.version}
author: janie177
main: com.minegusta.mgbossesredone.main.Main
commands:
  boss:
    description: The administrative Boss command.
    usage: /Boss
    aliases: [mgbosses, mgboss, mgb]
    permission: minegusta.boss